((:display_name "babel" :ssh_name "babel")
 (:display_name "5th ave workstation" :ssh_name "workstation")
 (:display_name "tpu v5 0" :ssh_name "v5e-tpu-128-0")
 (:display_name "tpu v5 1" :ssh_name "v5e-tpu-128-1")
 (:display_name "tpu v4 pod 0" :ssh_name "tpu_pod_64_0")
 (:display_name "tpu v4 pod 1" :ssh_name "tpu_pod_64_1")
 (:display_name "tpu v4 pod 2" :ssh_name "tpu_pod_64_2")
 (:display_name "tpu v4 pod 3" :ssh_name "tpu_pod_64_3")
 (:display_name "tpu v4 pod 4" :ssh_name "tpu_pod_64_4")
 (:display_name "tpu v4 0" :ssh_name "tpu_v4_0")
 (:display_name "tpu v4 1" :ssh_name "tpu_v4_1")
 (:display_name "tpu v4 2" :ssh_name "tpu_v4_2")
 (:display_name "tpu v4 3" :ssh_name "tpu_v4_3")
 (:display_name "tpu v4 4" :ssh_name "tpu_v4_4")
 (:display_name "tpu v4 5" :ssh_name "tpu_v4_5")
 (:display_name "tpu v4 6" :ssh_name "tpu_v4_6")
 (:display_name "tpu v4 7" :ssh_name "tpu_v4_7")
 (:display_name "Stanford" :ssh_name "sc.stanford.edu")
 (:display_name "Delta" :ssh_name "delta")
 )
